### ISSUE TITLE
Long intent text creates error?

### ISSUE THREAD

**Issue by trammell** [paranoia-game/pbot#1]
```
ERROR    asyncio  - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<SignalRouter._dispatch() done, defined at /Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/sanic/signals.py:121> exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/rasa/shared/utils/cli.py", line 12, in print_color
    from colorama import AnsiToWin32
ModuleNotFoundError: No module named 'colorama'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/sanic/signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/sanic/app.py", line 1581, in run_delayed_task

```

**Comment by trammell** [comment]
It looks like installing colorama (`pip install colorama`) fixes the ModuleNotFound error.

**Comment by trammell** [comment]
I think this is a manifestation of an error in asyncio exception handling, so resolving #2 should resolve this. Looking at the code, `colorama` is only needed on Win32 systems.
