### ISSUE TITLE
Long intent text causes asyncio error: BlockingIOError: [Errno 35] write could not complete without blocking

### ISSUE THREAD

**Issue by trammell** [paranoia-game/pbot#2]
```
Your input ->  statistics
The Character: Philo-R-DMD %d
Primary Attributes                      Secondary Attributes
===============================================================================
Strength ..................... 13       Carrying Capacity ................. 30
Endurance .................... 13       Damage Bonus ....................... 0
Agility ...................... 15       Macho Bonus ....................... -1
Manual Dexterity ............. 15       Melee Bonus ...................... +5%
Moxie ........................ 13       Aimed Weapon Bonus .............. +10%
Chutzpah ...................... 8       Comprehension Bonus .............. +4%
Mechanical Aptitude .......... 14       Believability Bonus .............. +5%
Power Index .................. 10       Repair Bonus ..................... +5%
===============================================================================
Credits: 160        Secret Society: Illuminati        Secret Society Rank: 1
Service Group: Power Services               Mu2022-11-15 11:04:15 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<SignalRouter._dispatch() done, defined at /Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/sanic/signals.py:121> exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/sanic/signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/sanic/app.py", line 1581, in run_delayed_task
    await prepped
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/rasa/core/run.py", line 135, in run_cmdline_io
    await console.record_messages(
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/rasa/core/channels/console.py", line 208, in record_messages

^C
    text = await _get_user_input(previous_response)
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/rasa/core/channels/console.py", line 120, in _get_user_input
    button_response = _print_bot_output(previous_response, is_latest_message=True)
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/rasa/core/channels/console.py", line 72, in _print_bot_output
    rasa.shared.utils.cli.print_color(message["text"], color=color)
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/rasa/shared/utils/cli.py", line 15, in print_color
    print(output, file=stream)
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/colorama/ansitowin32.py", line 47, in write
    self.__convertor.write(text)
  File "/Users/john/src/github.com/paranoia/pbot/.venv/lib/python3.8/site-packages/colorama/ansitowin32.py", line 179, in write
    self.wrapped.write(text)
BlockingIOError: [Errno 35] write could not complete without blocking


```

**Comment by trammell** [comment]
Background

* https://plainenglish.io/blog/how-to-manage-exceptions-when-waiting-on-multiple-asyncio
* https://realpython.com/async-io-python/
* https://docs.python.org/3.7/library/asyncio-eventloop.html#event-loop

Some chatter suggests this is due to stdout being nonblocking? It would be nice to reproduce this in a test setup.
